FROM oven/bun:latest
RUN apt-get update && apt upgrade -y && apt install -y curl unzip
# RUN curl -fsSL https://bun.sh/install | bash
COPY . /app
WORKDIR /app
RUN bun install
RUN bunx prisma migrate dev --name init
CMD ["bun", "index.ts"]
